export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_COMMCENTERS_BEGIN = "GET_COMMCENTERS_BEGIN";
export const GET_COMMCENTERS_SUCCESS = "GET_COMMCENTERS_SUCCESS";
export const GET_COMMCENTERS_FAIL = "GET_COMMCENTERS_FAIL";

export const FETCH_COMMCENTERS_BEGIN = "FETCH_COMMCENTERS_BEGIN";
export const FETCH_COMMCENTERS_SUCCESS = "FETCH_COMMCENTERS_SUCCESS";
export const FETCH_COMMCENTERS_FAIL = "FETCH_COMMCENTERS_FAIL";

export const FETCH_CONTROLLER_BEGIN = "FETCH_CONTROLLER_BEGIN";
export const FETCH_CONTROLLER_SUCCESS = "FETCH_CONTROLLER_SUCCESS";
export const FETCH_CONTROLLER_FAIL = "FETCH_CONTROLLER_FAIL";
export const SOCKET_UPDATE_CONTROLLER = "SOCKET_UPDATE_CONTROLLER";

export const FETCH_CONTROLLERS_FOR_COMMCENTER_BEGIN =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_BEGIN";
export const FETCH_CONTROLLERS_FOR_COMMCENTER_SUCCESS =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_SUCCESS";
export const FETCH_CONTROLLERS_FOR_COMMCENTER_FAIL =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_FAIL";
