export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_COMMCENTERS_BEGIN = "GET_COMMCENTERS_BEGIN";
export const GET_COMMCENTERS_SUCCESS = "GET_COMMCENTERS_SUCCESS";
export const GET_COMMCENTERS_FAIL = "GET_COMMCENTERS_FAIL";

export const FETCH_COMMCENTERS_BEGIN = "FETCH_COMMCENTERS_BEGIN";
export const FETCH_COMMCENTERS_SUCCESS = "FETCH_COMMCENTERS_SUCCESS";
export const FETCH_COMMCENTERS_FAIL = "FETCH_COMMCENTERS_FAIL";
export const UPDATE_COMMCENTERS = "UPDATE_COMMCENTERS";

export const FETCH_COMMCENTER_MONITORING_BEGIN =
  "FETCH_COMMCENTER_MONITORING_BEGIN";
export const FETCH_COMMCENTER_MONITORING_SUCCESS =
  "FETCH_COMMCENTER_MONITORING_SUCCESS";
export const FETCH_COMMCENTER_MONITORING_FAIL =
  "FETCH_COMMCENTER_MONITORING_FAIL";
export const SOCKET_UPDATE_COMMCENTER_MONITORING =
  "SOCKET_UPDATE_COMMCENTER_MONITORING";

export const FETCH_CONTROLLERS_FOR_COMMCENTER_BEGIN =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_BEGIN";
export const FETCH_CONTROLLERS_FOR_COMMCENTER_SUCCESS =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_SUCCESS";
export const FETCH_CONTROLLERS_FOR_COMMCENTER_FAIL =
  "FETCH_CONTROLLERS_FOR_COMMCENTER_FAIL";

export const FETCH_MAP_COMMCENTERS_BEGIN = "FETCH_MAP_COMMCENTERS_BEGIN";
export const FETCH_MAP_COMMCENTERS_SUCCESS = "FETCH_MAP_COMMCENTERS_SUCCESS";
export const FETCH_MAP_COMMCENTERS_FAIL = "FETCH_MAP_COMMCENTERS_FAIL";
export const UPDATE_MAP_COMMCENTERS = "UPDATE_MAP_COMMCENTERS";

export const FETCH_CURRENT_COMMCENTER_BEGIN = "FETCH_CURRENT_COMMCENTER_BEGIN";
export const FETCH_CURRENT_COMMCENTER_SUCCESS =
  "FETCH_CURRENT_COMMCENTER_SUCCESS";
export const FETCH_CURRENT_COMMCENTER_FAIL = "FETCH_CURRENT_COMMCENTER_FAIL";
export const UPDATE_CURRENT_COMMCENTER = "UPDATE_CURRENT_COMMCENTER";
